"""Reconstruct the full 985-subject IHDP dataset (all treated infants).

Hill's NPCI benchmark dropped treated infants with non-white mothers, leaving
139 treated / 608 control = 747 subjects (~19% treated). The full dataset
has 377 treated / 608 control = 985 subjects (~38% treated).

This benchmark was generated as "Response Surface B" (see Hill's paper Bayesian
Nonparametric Modeling for Causal Inference), which is as follows:

    Y(0) ~ N(exp((X + W)β), 1) and Y(1) ~ N(Xβ - ω, 1)

where

    W -- offset matrix of same dimension as X, every value equal to 0.5
    β -- regression coefﬁcients vector of length 26 (25 covariates + 1 intercept)
         with each element randomly sampled from (0, 0.1, 0.2, 0.3, 0.4) with
         probabilities (0.6, 0.1, 0.1, 0.1, 0.1)
    ω -- scalar chosen s.t. CATE for both treated and control groups (CATT and CATC,
         respectively) equals 4

The key takeaway is that the outcomes mu0 and mu1 are generated from a
deterministic function of the covariates, and the observed outcomes y_factual
and y_cfactual are generated by adding Gaussian noise to mu0 and mu1. Therefore,
we can reconstruct the outcomes for the additional treated subjects by fitting
a simple linear regression.

Strategy per replication:
  1. Fit log(mu0) ~ X and mu1 ~ X on the 747 NPCI subjects (R²=1 -- exact).
  2. Apply to all 985 subjects using per-column linear-scaled covariates.
  3. Keep original y_factual/y_cfactual for the 747 existing subjects.
  4. Generate y0=mu0+N(0,sigma), y1=mu1+N(0,sigma) for the 238 new subjects,
     then set y_factual=(1-a)*y0+a*y1, y_cfactual=a*y0+(1-a)*y1.

Output format matches ihdp_with_race_*.csv:
  treat, y_factual, y_cfactual, mu0, mu1, <25 covariates>, momwhite, momblack, momhisp
"""

from pathlib import Path
from typing import cast

import numpy as np
import pandas as pd
import pyreadr
from sklearn.linear_model import LinearRegression

# -- Column definitions --------------------------------------------------------

CONTINOUS_VARS = ["bw", "b.head", "preterm", "birth.o", "nnhealth", "momage"]
# fmt: off
BINARY_VARS = [
    "sex", "twin", "b.marr", "mom.lths", "mom.hs", "mom.scoll",
    "cig", "first", "booze", "drugs", "work.dur", "prenatal",
]
# fmt: on
SITE_INDICATORS = ["ark", "ein", "har", "mia", "pen", "tex", "was"]

COVARIATE_COLS = [*CONTINOUS_VARS, *BINARY_VARS, *SITE_INDICATORS]  # 25 covariates
NPCI_COLS = ["treat", "y_factual", "y_cfactual", "mu0", "mu1", *COVARIATE_COLS]

NUM_REPLICATIONS = 10
SEED = 42

# betaB entries are drawn from this grid (sim.code.overlap.R); used to
# validate and denoise the regression-recovered slope coefficients below.
BETA_GRID = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
BETA_GRID_TOL = 1e-6

HERE = Path(__file__).parent

# -- Load the full 985-subject covariate+treatment+race data -------------------

result = pyreadr.read_r(str(HERE / "sim.data"))
imp1: pd.DataFrame = result["imp1"]  # 985 × 29  (treat + 25 covariates + 3 race)

# Boolean mask: which imp1 rows are the 747 NPCI subjects
npci_mask = (imp1["treat"] == 0) | (imp1["momwhite"] == 1)
assert npci_mask.sum() == 747
assert (~npci_mask).sum() == 238

# 747 subjects, same order as NPCI CSVs
imp1_npci = cast(pd.DataFrame, imp1[npci_mask].reset_index(drop=True))
# 238 additional treated subjects
imp1_new = cast(pd.DataFrame, imp1[~npci_mask].reset_index(drop=True))

# -- Recover per-column linear transform: raw imp1 -> NPCI-scale ---------------
# Estimated from replication 1 (same covariates across all reps)

npci_ref = pd.read_csv(
    HERE / "npci" / "ihdp_npci_1.csv",
    names=NPCI_COLS,
    index_col=False,
)
raw_ref_x = imp1_npci[COVARIATE_COLS].values.astype(float)
npci_ref_x = npci_ref[COVARIATE_COLS].values.astype(float)

# Compute per-column linear transform: raw imp1 -> NPCI-scale
# np.cov defaults to ddof=1; np.var must match or the slope is biased by
# N/(N-1) (confirmed empirically: 747/746 = 1.001340, exactly the erroneous
# slope this produced for every binary column before the ddof was fixed).
slopes = np.array(
    [
        np.cov(raw_ref_x[:, i], npci_ref_x[:, i], ddof=1)[0, 1]
        / np.var(raw_ref_x[:, i], ddof=1)
        for i in range(len(COVARIATE_COLS))
    ]
)
intercepts = npci_ref_x.mean(axis=0) - slopes * raw_ref_x.mean(axis=0)

# The fitted slope/intercept recovers binary data near-exactly (~1e-15 off)
# Snap these columns to the nearest integer to remove that floating-point noise
INTEGER_COL_IDX = [COVARIATE_COLS.index(c) for c in [*BINARY_VARS, *SITE_INDICATORS]]


def to_npci_scale(raw_x: np.ndarray) -> np.ndarray:
    scaled = raw_x * slopes + intercepts
    scaled[:, INTEGER_COL_IDX] = np.round(scaled[:, INTEGER_COL_IDX])
    return scaled


X_npci = to_npci_scale(imp1_npci[COVARIATE_COLS].values.astype(float))  # 747 × 25
X_new = to_npci_scale(imp1_new[COVARIATE_COLS].values.astype(float))  # 238 × 25
X_all = to_npci_scale(imp1[COVARIATE_COLS].values.astype(float))  # 985 × 25

# -- Generate replications ----------------------------------------------------

rng = np.random.default_rng(SEED)
out_dir = HERE / "full"
out_dir.mkdir(exist_ok=True)

beta_records = []

for rep in range(1, NUM_REPLICATIONS + 1):
    npci = pd.read_csv(
        HERE / "npci" / f"ihdp_npci_{rep}.csv",
        names=NPCI_COLS,
        index_col=False,
    )

    # -- Fit DGP from 747 NPCI subjects (this is exact -- R²=1) ---------------
    mu0_npci = npci["mu0"].values
    mu1_npci = npci["mu1"].values
    reg0 = LinearRegression().fit(X_npci, np.log(mu0_npci))
    reg1 = LinearRegression().fit(X_npci, mu1_npci)

    # betaB's slope vector is shared between log(mu0) and mu1 (they differ
    # only in intercept, by the CATT-calibration offset omega), and every
    # entry is independently drawn from BETA_GRID. Both facts must hold if
    # the recovered X_npci transform and regression setup are correct --
    # verify, then snap to the grid to remove residual floating-point noise.
    assert np.allclose(reg0.coef_, reg1.coef_, atol=BETA_GRID_TOL), (
        f"rep {rep}: reg0/reg1 slopes disagree, "
        f"max diff={np.max(np.abs(reg0.coef_ - reg1.coef_)):.2e}"
    )
    for name, coef in [("reg0 (log mu0)", reg0.coef_), ("reg1 (mu1)", reg1.coef_)]:
        nearest = BETA_GRID[np.abs(coef[:, None] - BETA_GRID).argmin(axis=1)]
        max_err = np.max(np.abs(coef - nearest))
        assert max_err < BETA_GRID_TOL, (
            f"rep {rep} {name}: coef off grid, max_err={max_err:.2e}"
        )

    coefs_snapped = BETA_GRID[np.abs(reg1.coef_[:, None] - BETA_GRID).argmin(axis=1)]
    reg0.coef_ = coefs_snapped.copy()
    reg1.coef_ = coefs_snapped.copy()

    # Noise sigma is a fixed DGP constant (sigy=1 in sim.code.overlap.R), not
    # something to estimate -- the ~0.98-0.99 empirical std over 747 subjects
    # is just finite-sample noise around the true value of 1.
    sigma = 1.0

    # -- Predict mu0, mu1 -----------------------------------------------------
    # Rows that correspond to the 747 NPCI subjects
    npci_idx = np.where(npci_mask.values)[0]
    new_idx = np.where(~npci_mask.values)[0]

    mu0_all = np.exp(reg0.predict(X_all))
    mu1_all = reg1.predict(X_all)
    # Predictions are only needed for the 238 new subjects -- for the 747
    # known subjects, use the exact published values instead of the (near-
    # exact but not bit-identical) regression reconstruction.
    mu0_all[npci_idx] = mu0_npci
    mu1_all[npci_idx] = mu1_npci

    # -- Build output dataframe (985 rows, same order as imp1) ----------------
    treatment_all = imp1["treat"].values.astype(float)

    # The offset baked into mu1 was calibrated so CATT=4 over the *original*
    # 139 treated subjects only. Response surface B has a heterogeneous
    # treatment effect (mu1 linear, mu0 exponential in X), so adding 238
    # treated subjects with a different covariate distribution shifts the
    # realized CATT away from exactly 4 -- report the actual values.
    te_all = mu1_all - mu0_all
    catt_full = te_all[treatment_all == 1].mean()
    catc_full = te_all[treatment_all == 0].mean()
    ate_full = te_all.mean()

    # reg0/reg1 intercepts differ by exactly the CATT-calibration offset omega
    # (see comment above: log(mu0) and mu1 share betaB's slope vector, differing
    # only in intercept) -- reg1.intercept_ = reg0.intercept_ - omega.
    beta_records.append(
        {
            "replication": rep,
            "treatment_rate": treatment_all.mean(),
            "mu0_min": mu0_all.min(),
            "mu0_max": mu0_all.max(),
            "mu1_min": mu1_all.min(),
            "mu1_max": mu1_all.max(),
            **dict(zip(COVARIATE_COLS, coefs_snapped, strict=True)),
            "intercept": reg0.intercept_,
            "catt_calibration_offset": reg0.intercept_ - reg1.intercept_,
            "CATT": catt_full,
            "CATC": catc_full,
            "ATE": ate_full,
        }
    )

    out = pd.DataFrame()
    out["treat"] = treatment_all
    out["mu0"] = mu0_all
    out["mu1"] = mu1_all

    # y_factual / y_cfactual: keep original for 747, generate for 238
    y_fac_all: np.ndarray = np.empty(985)
    y_cfac_all: np.ndarray = np.empty(985)

    y_fac_all[npci_idx] = npci["y_factual"].values
    y_cfac_all[npci_idx] = npci["y_cfactual"].values

    # New treated subjects: sample y0 and y1 from DGP
    mu0_new = mu0_all[new_idx]
    mu1_new = mu1_all[new_idx]
    y0_new = mu0_new + rng.normal(0, sigma, size=len(new_idx))
    y1_new = mu1_new + rng.normal(0, sigma, size=len(new_idx))
    treatment_new = treatment_all[new_idx]  # all 1 (treated)
    y_fac_all[new_idx] = (1 - treatment_new) * y0_new + treatment_new * y1_new
    y_cfac_all[new_idx] = treatment_new * y0_new + (1 - treatment_new) * y1_new

    out["y_factual"] = y_fac_all
    out["y_cfactual"] = y_cfac_all

    # Covariates (NPCI-scale)
    for j, col in enumerate(COVARIATE_COLS):
        out[col] = X_all[:, j]

    # Race
    out["momwhite"] = imp1["momwhite"].values
    out["momblack"] = imp1["momblack"].values
    out["momhisp"] = imp1["momhisp"].values

    # Reorder to match ihdp_with_race column order
    final_cols = (
        ["treat", "y_factual", "y_cfactual", "mu0", "mu1"]
        + COVARIATE_COLS
        + ["momwhite", "momblack", "momhisp"]
    )
    out = out[final_cols]

    path = out_dir / f"ihdp_full_{rep}.csv"
    out.to_csv(path, index=False)
    print(
        f"Rep {rep:2d}: N={len(out)}  treat_rate={treatment_all.mean():.3f}"
        f"  mu0=[{mu0_all.min():.2f},{mu0_all.max():.2f}]"
        f"  mu1=[{mu1_all.min():.2f},{mu1_all.max():.2f}]"
        f"  sigma={sigma:.4f}"
        f"  CATT={catt_full:.3f}  CATC={catc_full:.3f}  ATE={ate_full:.3f}"
    )

print(f"\nSaved {NUM_REPLICATIONS} replications to {out_dir}/")

beta_path = out_dir / "beta_coefficients.csv"
pd.DataFrame(beta_records).to_csv(beta_path, index=False)
print(f"Saved beta coefficients to {beta_path}")
